---
url: https://www.emfink.net
baseurl: /CivProBook
title: Civil Procedure
description: An Open-Source Casebook

last_updated: 11 August 2025

author:
  name: Eric M. Fink
  positition: Associate Professor
  affiliation: Elon Law School
  address: 201 North Greene Street
  city: Greensboro
  state: North Carolina 
  zip: '27408'
  email: efink@elon.edu
  phone: 336-279-9334
  web: emfink.net/ElonLaw

coursebook:
  title: Civil Procedure
  subtitle: An Open-Source Casebook
  version: '4.0'
  date: September 2025