project:
    type: tufte
book:
  open-graph: true
  site-url: https://www.emfink.net/CivProCasebook
  repo-url: https://github.com/EricMFink/CivProCasebook/
  repo-actions: [issue]
  downloads: [pdf]
  sidebar:
    tools:
      - icon: github
        href: https://github.com/EricMFink/CivProCasebook
      - icon: page-pdf
        href: ./CivProCasebook.pdf
  title: Civil Procedure
  subtitle: An Open-Source Casebook
  title-short: Civil Procedure # title-short is used in the pdf head
  output-file: CivProCasebook # outputs: docs/CivProBook.pdf
  chapters:
    - index.qmd
    - part: "Front Matter"
      chapters:
        - 01-Front/license.qmd
        - 01-Front/epigraph.qmd
        - 01-Front/preface.qmd
    - part: "Chapters"
      chapters:
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 02-Main/chap3.qmd
        - 02-Main/chap4.qmd
        - 02-Main/chap5.qmd
        - 02-Main/chap6.qmd
        - 02-Main/chap7.qmd
        - 02-Main/chap8.qmd
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
bibliography: ./bib/CivProBook.yaml
csl: ./bib/casebook-bibliography.csl

