project:
    type: tufte

book:
  site-url: "https://www.emfink.net/{{< var path >}}/"
  repo-url: "https://github.com/EricMFink/{{< var path >}}"
  output-file: "{{< var path >}}"
  title: "{{< var title >}}"
  subtitle: An Open-Source Casebook
  author:
  - name: Eric M. Fink
    email: efink@elon.edu
    affiliations:
      - name: Elon University School of Law
        address: 201 North Greene Street
        city: Greensboro
        state: North Carolina
        postal-code: 27278
  sidebar:
    downloads: [pdf]
    tools:
      - icon: github
        menu:
          - text: View source code.
            href: https://github.com/EricMFink/{{< var path >}}/
          - text: Report an issue.
            href: https://github.com/EricMFink/{{< var path >}}/issues/new
  chapters:
    - index.qmd
    - part: "Front Matter"
      chapters:
        - 01-Front/license.qmd
        - 01-Front/epigraph.qmd
        - 01-Front/preface.qmd
    - part: "Chapters"
      chapters:
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 02-Main/chap3.qmd
        - 02-Main/chap4.qmd
        - 02-Main/chap5.qmd
        - 02-Main/chap6.qmd
        - 02-Main/chap7.qmd
        - 02-Main/chap8.qmd
    - part: "Back Matter"
      chapters:
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
format:
  html
csl: ./bib/casebook-bibliography.csl
bibliography: bib/{{< var path >}}.yaml