# Front Matter {.unnumbered}

::: {.license}

{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}} 

All original content is licensed under a [Creative Commons Attribution NonCommercial ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

## Eric M. Fink
### Associate Professor of Law
### Elon University School of Law
### Greensboro, North Carolina 27408
#### [emfink.net/ElonLaw](https://www.emfink.net/ElonLaw)

Source code: [github.com/EricMFink/CivProBook](https://github.com/EricMFink/CivProBook) 

_Version 4.1, August 2025_

---

:::

::: {.epigraph}

## [Epigraph]{.invisible .unlisted}

> Jarndyce and Jarndyce drones on. This scarecrow of a suit has, in course of time, become so complicated that no man alive knows what it means. The parties to it understand it least, but it has been observed that no two Chancery lawyers can talk about it for five minutes without coming to a total disagreement as to all the premises. Innumerable children have been born into the cause; innumerable young people have married into it; innumerable old people have died out of it. Scores of persons have deliriously found themselves made parties in Jarndyce and Jarndyce without knowing how or why; whole families have inherited legendary hatreds with the suit. The little plaintiff or defendant who was promised a new rocking-horse when Jarndyce and Jarndyce should be settled has grown up, possessed himself of a real horse, and trotted away into the other world. Fair wards of court have faded into mothers and grandmothers; a long procession of Chancellors has come in and gone out; the legion of bills in the suit have been transformed into mere bills of mortality; there are not three Jarndyces left upon the earth perhaps since old Tom Jarndyce in despair blew his brains out at a coffee-house in Chancery Lane; but Jarndyce and Jarndyce still drags its dreary length before the court, perennially hopeless.
 
[{{< fa solid pen-nib >}}]{.theme-color} [@Dickens2003]

:::