# Preface {.unnumbered}

This book presents material for use in a first-year law school Civil Procedure course. Topics covered include the scope of a lawsuit (Party & Claim Joinder), selection of an appropriate forum (Personal & Subject Matter Jurisdiction), presentation of claims and defenses (Pleadings), choice of applicable law (the _Erie_ doctrine & the Rules Enabling Act), disposition without a trial (Summary Judgment), and the effect of judgments on future litigation (Claim & Issue Preclusion).

Most of the materials reproduced here are in the public domain; excerpts from copyrighted materials are included for teaching purposes under the fair use doctrine. Materials have been redacted to omit passages not pertinent to the learning objectives. Judicial opinions have also been "cleaned up" for ease of reading.[^Preface1] 

[^Preface1]: _See_ [@Metzler2017] (proposing "cleaned up" parenthetical for quotations from judicial opinions, to indicate the author “has removed extraneous, non-substantive material like brackets, quotation marks, ellipses, footnote reference numbers, and internal citations; may have changed capitalization without using brackets to indicate that change; and affirmatively represents that the alterations were made solely to enhance readability and that the quotation otherwise faithfully reproduces the quoted text.”) 

### Site Navigation & Viewing Options 

You can navitgate through the parts of this book using the sidebar index. You can also navigate forwards and backwards using the arrows at the bottom of each page. 

The buttons beneath the title in the sidebar offer these options:

::: {.unstyled}

- [{{< bi github >}}]{.link-color}&nbsp; View the source code on GitHub
- [{{< bi file-pdf >}}]{.link-color}&nbsp; View and download a PDF copy
- {{< bi body-text >}}&nbsp; Reader mode: Hide sidebar in a collapsable menu

:::

You can report typographical errors or technical issues by using the button at the bottom of the sidebar.[^issues1]

[^issues1]: Issue reporting requires a [GitHub](https://github.com/) account. It's free and a very useful resource. 

### Sidenotes & Margin Notes

Following the style of [Edward Tufte](https://www.edwardtufte.com/tufte/), this book uses sidenotes and margin notes in place of traditional footnotes or endnotes. These appear in the right-hand margin, avoiding the need to jump through hyperlinks or scroll to the note text.

Numbered sidenotes[^sidenote] are used for footnotes in the source materials (with original note numbering indicated in parentheses). 

[^sidenote]: This is an example of a sidenote. 

Unnumbered margin notes [This is an example of a margin note.]{.aside} ([green sans-serif typeface]{.margin-note}) are used for editor's comments within cases. 

### Links

Links to cross-referenced pages or external material are indicated by [dark red]{.link-color} text, e.g. [U.S. Department of Labor](https://www.dol.gov/). 